CREATE DATABASE teste;

USE teste;

CREATE TABLE CLIENTE (
	id INTEGER PRIMARY KEY AUTO_INCREMENT, 
	cpf VARCHAR(250), 
	nome VARCHAR(250)
);

CREATE TABLE VEICULO (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  renavam VARCHAR(250),
  marca VARCHAR(250),
  modelo  VARCHAR(250),
  valorDiaria DOUBLE
);

CREATE TABLE LOCACAO (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	cliente_id INTEGER,
	veiculo_id INTEGER,
	dataInicio VARCHAR(10),
	dataFim VARCHAR(10),
	valorTotal DOUBLE
);

ALTER TABLE LOCACAO ADD CONSTRAINT FK_cliente_id FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id);

ALTER TABLE LOCACAO ADD CONSTRAINT FK_veiculo_id FOREIGN KEY (veiculo_id) REFERENCES VEICULO(id);

SELECT * FROM VEICULO;
